CREATE TABLE dukan.product (id INTEGER NOT NULL PRIMARY AUTO_INCREMENT, product_name TEXT NOT NULL, product_price DECIMAL NOT NULL, PRIMARY KEY (product_id) );

CREATE TABLE `dukan`.`products` (`id` int NOT NULL AUTO_INCREMENT, `name` TEXT NOT NULL, `sku` VARCHAR(50) NOT NULL,  `description` TEXT NOT NULL, `short_description` TEXT NOT NULL, `createddate` datetime NOT NULL, `updatedate` datetime NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `id_UNIQUE` (`id`), UNIQUE KEY `sku_UNIQUE` (`sku`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='This table is used to store the basic information about the product';

INSERT INTO `dukan`.`products` (`name`, `sku`, `description`, `short_description`, `createddate`, `updatedate`) VALUES ('Samsung Galaxy M51', 'RZ8NB0AA3FA', '<ul class="a-unordered-list a-vertical a-spacing-mini">  <li class="a-spacing-mini"><span class="a-list-item"> Monster Durability &amp; Display : Corning Gorilla Glass Victus+, 16.83 Centimeters (6.6"Inch) Super AMOLED Display, FHD+ Resolution with 1080 x 2340 Pixels and 120Hz Refresh Rate  </span></li>  <li class="a-spacing-mini"><span class="a-list-item"> Monster Processor - Exynos 1380 Processor with Vapour Cooling Chamber | Latest Android 14 Operating System having One UI 6.1 platform | 2.4GHz, 2GHz Clock Speed with Octa-Core Processor  </span></li>  <li class="a-spacing-mini"><span class="a-list-item"> Monster Convenience &amp; Security - Samsung Wallet with Tap &amp; Pay | Knox Security | Get upto 4 Generations of AndroidOS Upgrades &amp; 5 Years of Security Updates  </span></li>  <li class="a-spacing-mini"><span class="a-list-item"> Monster Camera - 50MP (F1.8) Main Wide Angle Camera + 8MP (F2.2) Ultra Wide Angle Camera + 2MP (F2.4) Macro Angle Camera | OIS &amp; Nightography | 13MP (F2.2) Selfie Camera | Video Maximum Resolution of Ultra HD (3840 x 2160) @30fps  </span></li>  <li class="a-spacing-mini"><span class="a-list-item"> Monster Battery - Get a massive 6000mAh Lithium-ion Battery (Non-Removable) with C-Type Fast Charging (25W Charging Support)  </span></li>  </ul>', '<span id="productTitle" class="a-size-large product-title-word-break">        Samsung Galaxy M35 5G (Thunder Grey,6GB RAM,128GB Storage)| Corning Gorilla Glass Victus+| AnTuTu Score 595K+ | Vapour Cooling Chamber | 6000mAh Battery | 120Hz Super AMOLED Display| without Charger       </span>', '2024-08-11', '2024-08-11');


Error Code: 1170. BLOB/TEXT column 'sku' used in key specification without a key length


CREATE TABLE `dukan`.`products` (`id` int NOT NULL AUTO_INCREMENT, `name` TEXT NOT NULL, `sku` VARCHAR(50) NOT NULL,  `description` TEXT NOT NULL, `short_description` TEXT NOT NULL, `createddate` datetime NOT NULL, `updatedate` datetime NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `id_UNIQUE` (`id`), UNIQUE KEY `sku_UNIQUE` (`sku`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='This table is used to store the basic information about the product';

CREATE TABLE `dukan`.`products1` (`id` int NOT NULL AUTO_INCREMENT, `name` TEXT NOT NULL, `sku` VARCHAR(50) NOT NULL,  `description` TEXT NOT NULL, `short_description` TEXT NOT NULL, `createddate` datetime NOT NULL, `updatedate` datetime NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `id_UNIQUE` (`id`), UNIQUE KEY `sku_UNIQUE` (`sku`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='This table is used to store the basic information about the product';

Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAU' at line 1

